### ISSUE TITLE
Energy consuption

### ISSUE THREAD

**Issue by TheoMarque** [4a2e532e/RealisticSwimming#2]
Player when swimming fast or dive must use own energy or health to do.

suggested config:

```
## Exahustion ##
base: 0.8
depth: true
## Multiplier, when player goes deeper increase linear ##
  by_y: 1.02 
speed: true
  normal: 1.01
  sprint: 1.20
fall_to_shallow_water_damage: false
  ## number of water blocks ##
  shallow_water: 2
  ## percentage dealt ##
  damage:10  
```

**Comment by Legoman99573** [comment]
sounds nice. but could exahustion be disableable as some wouldnt use it. (not saying this is a bad idea)

**Comment by 4a2e532e** [comment]
Of course you can disable it.
Once it is released (probably in two or three days), there will be a config option to disable/enable it (as it is a huge change, it will probably be disabled by default).
