### ISSUE TITLE
[Suggestion] Add dive animation

### ISSUE THREAD

**Issue by ShadowCable** [4a2e532e/RealisticSwimming#3]
Can you add a dive animation when jumping off something. May wanna configure it to work with the elytra staring down and falling fast type event or something ;)

**Comment by ShadowCable** [comment]
I would go far and add it to any height over water. Here is a config option that could be added.

(hashtag) How many blocks until a fall animation takes place. Values lower than the value set will not use the animation.
Blocks-until-fall-animation-in-water: 4

Permission node: rs.user.dive

**Comment by 4a2e532e** [comment]
I created an experimental branch and added EXPERIMENTAL fall and sneak animations.
